# Configuration file
# key = value
greeting:
  name: Simeão
user:
  name: David Lamine

quarkus:
  http:
    port: 3000

  jeager:
    service-name: quarkus-basic
    sampler-type: const
    sampler-param: 1
    endpoint: http://localhost:14268/api/traces

  datasource:
    url: jdbc:mysql://localhost:3306/quarkusbasic
    username: root
    password: root
    driver: org.mariadb.jdbc.Driver

    hibernate-orm:
      database:
        generation: update


br:
  slamine:
    com:
      HelloClient/mp-rest/url: http://localhost:8080